Improved Alpha channel and Transparency for exporting JSON material
OGRECave/blender2ogre pull request #185
Opened 2023-11-07 12:32 UTC by knn217

_Images plugged into "Principled BSDF" 's Alpha will combine with Images at BaseColor as the alpha channel (Since Ogre use 1 image for both color and alpha).

_More options for texture's BlendBlock, controlled by Blender's 3 Blend modes:
* Alpha clip = just Blend Type: REPLACE
* Alpha Blend = a BlendBlock with custom setting, very transparent
* Alpha Hashed =  a BlendBlock with custom setting but less transparent than Alpha Blend

_There was plan for supporting other texture nodes aside from image, but I couldn't find a way to get the node's color matrices

2023-11-08 23:27 UTC, paroj commented
> Here's what my setup look like for combining Base Color texture and Alpha texture: ![image](https://user-images.githubusercontent.com/86541274/281060632-82193a52-7c31-43b8-ba7c-d2d6ed605267.png)

I dont think there is much value for supporting a separate alpha texture. We should rather assume that the alpha channel of the base texture is used, if present.

2023-11-08 23:40 UTC, paroj commented
>     * Alpha Clip = just Blend Type: REPLACE
> 
>     * Alpha Blend = a BlendBlock with custom setting, very transparent
> 
>     * Alpha Hashed =  a BlendBlock with custom setting but less transparent than Alpha Blend

this does not make sense. Alpha clip should map to  [alpha_rejection](https://ogrecave.github.io/ogre/api/14/_material-_scripts.html#autotoc_md138) or whatever it is called in ogre next.

 Alpha Hashed  must be equal to Alpha Blend.

2023-11-08 23:51 UTC, knn217 commented
> > Here's what my setup look like for combining Base Color texture and Alpha texture: ![image](https://user-images.githubusercontent.com/86541274/281060632-82193a52-7c31-43b8-ba7c-d2d6ed605267.png)
> 
> I dont think there is much value for supporting a separate alpha texture. We should rather assume that the alpha channel of the base texture is used, if present.

Yes, the code also support this! 
If you plugged the Alpha channel of Base Color texture into Map Range, it will also work:
![image](https://github.com/OGRECave/blender2ogre/assets/86541274/17e29423-7a11-4385-9b7b-b9f59c3a2623)

The "Map Range" node is required since the code uses this to determine ["Transparency"]["value"], this was originally determined by the alpha channel's default value of Principled BSDF, but it is overwritten if plugged in so I changed this to "Map Range" so that the effects are more in sync between Blender and Ogre.

2023-11-09 00:20 UTC, knn217 commented
> > ```
> > * Alpha Clip = just Blend Type: REPLACE
> > 
> > * Alpha Blend = a BlendBlock with custom setting, very transparent
> > 
> > * Alpha Hashed =  a BlendBlock with custom setting but less transparent than Alpha Blend
> > ```
> 
> this does not make sense. Alpha clip should map to [alpha_rejection](https://ogrecave.github.io/ogre/api/14/_material-_scripts.html#autotoc_md138) or whatever it is called in ogre next.
> 
> Alpha Hashed must be equal to Alpha Blend.

Yes, I think it is "alpha_test" in Ogre-next.
You are right about Alpha clip, it actually doesn't need a BlendBlock, I just need to set "Transparency" mode to "None" but I was copy pasting that code section since it have the same effect, but yeah this might confuse the user, I'll change it back.

About Alpha Hashed, I also thought its basically the same as Alpha Blend, so I made it have a different Blend type to make use of this slot. I can change it back to be the same as Alpha Blend tho.

2023-11-09 15:22 UTC, paroj commented
sorry for not being clear previously: I think that we explicitly *should not* handle the cases that you are currently implementing, particularly:

> I also added in a feature that can combine alpha texture with "base color" value if there's no diffuse texture, so a setup like this:

and

> The "Map Range" node is required since the code uses this to determine ["Transparency"]["value"]

this complicates code that needs to be maintained moving forward and is only specific to one usecase. This should rather be offloaded to the user before the exporter is run.

Also note, that imagick presence is optional so you cannot rely on being able to use it for fixing things. The export should succeed even without imagick.

2023-11-09 15:25 UTC, paroj requested changes

2023-11-09 15:25 UTC, paroj commented on io_ogre/ogre/material.py
> +def gather_alpha_texture(mat_wrapper):
please remove this function altogether, the code was sufficient before.

2023-11-09 15:25 UTC, paroj commented on io_ogre/ogre/materialv2json.py
> +                logger.debug("No diffuse texture found, combining alpha channel with Principled BSDF's base color value")
please remove this functionality

2023-11-09 15:25 UTC, paroj commented on io_ogre/ogre/materialv2json.py
> +                    logger.warning("The Alpha texture used on material '{}' is not from the same file as "
please remove this functionality

2023-11-09 15:33 UTC, knn217 commented
OK, so only remove the alpha texture code right?

2023-11-09 16:37 UTC, knn217 commented
Changes were applied, please check to see if I missed anything.

2023-11-09 16:56 UTC, merged