Sincronize 2.8+ compatible changes made to 2.7x-support branch with master branch
OGRECave/blender2ogre pull request #71
Opened 2021-03-06 21:54 UTC by sercero

Synchronize recent changes made to the 2.7x-support branch:

- Support for add-on script reload
- Inhibit export of any user properties when EXPORT_USER is not selected
- Add Particle system random object distribution

2021-03-08 17:55 UTC, paroj requested changes

2021-03-08 21:48 UTC, sercero commented on io_ogre/config.py
> +    'EXPORT_USER' : True,
There are other properties

2021-03-08 21:49 UTC, sercero commented on io_ogre/ogre/scene.py
> +            print("ABABA", ob.name)
Do you know why that "ABABA" is there?

2021-03-09 12:51 UTC, paroj commented on io_ogre/config.py
> +    'EXPORT_USER' : True,
let me rephrase: when exporting the cube with 2.80+ I get an empty `userData`. So to get extra properties, one has to explicitly request them and this additional toggle is not needed. In contrast, with 2.7x you always get some dummy physics values.

Getting rid of the empty `userData`, should be rather a check whether there are any properties to be exported.

2021-03-10 01:33 UTC, sercero commented on io_ogre/config.py
> +    'EXPORT_USER' : True,
OK, I understand

2021-03-10 01:46 UTC, sercero commented on io_ogre/config.py
> +    'EXPORT_USER' : True,
Pushed new changes

2021-03-10 11:46 UTC, merged